// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xowxgbovrbnpsreqgrlt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhvd3hnYm92cmJucHNyZXFncmx0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY3MTExMTQsImV4cCI6MjA2MjI4NzExNH0.-ImCtHAPnA84ZBoSdmqnGLI25GiqbDkl0rjLeHXe87k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);